openapi: 3.0.1
info:
  title: '@jupiterone/graph-hackerone'
  description: A JupiterOne managed integration for https://www.hackerone.com/
  x-cortex-git:
    github:
      repository: JupiterOne/graph-hackerone
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-hackerone'
  x-cortex-service-groups:
    - tier-4
